const INTUSTRY_LIST = [
    {
        name: '房地产',
        id: 1,
        description: ''
    },
    {
        name: '市政工程',
        id: 2,
        description: ''
    }, /*{
        name: '市政道路建设'
    },*/
    {
        name: '市政公用设施建设',
        id: 3,
        description: ''
    }, {
        name: '自来水输水工程',
        id: 4,
        description: ''
    }, {
        name: '集中供暖、供热、供气工程',
        id: 5,
        description: ''
    }, {
        name: '文教、卫生、体育、音乐等公益设施建设',
        id: 6,
        description: ''
    }, {
        name: '纪念性建筑设施建设',
        id: 7,
        description: ''
    }, {
        name: '各类建筑工程',
        id: 8,
        description: ''
    }, {
        name: '木材板材',
        id: 9,
        description: ''
    }, {
        name: '石材石料',
        id: 10,
        description: ''
    }, {
        name: '水泥及制品',
        id: 11,
        description: ''
    }, {
        name: '石灰',
        id: 12,
        description: ''
    }, {
        name: '石膏',
        id: 13,
        description: ''
    }, {
        name: '混凝土及制品',
        id: 14,
        description: ''
    }, {
        name: '建筑玻璃',
        id: 15,
        description: ''
    }, {
        name: '陶瓷',
        id: 16,
        description: ''
    }, {
        name: '搪瓷及制品',
        id: 17,
        description: ''
    }, {
        name: '塑料建材',
        id: 18,
        description: ''
    }, {
        name: '金属建材',
        id: 19,
        description: ''
    }, {
        name: '防水',
        id: 20,
        description: ''
    }, {
        name: '防潮材料',
        id: 21,
        description: ''
    }, {
        name: '耐火',
        id: 22,
        description: ''
    }, /*{
        name: '防火材料',
        id: 1,
        description: ''
    }, {
        name: '隔热',
        id: 1,
        description: ''
    }, {
        name: '吸声材料',
        id: 1,
        description: ''
    }, {
        name: '绝缘材料',
        id: 1,
        description: ''
    }, {
        name: '特种建材',
        id: 1,
        description: ''
    }, {
        name: '施工材料',
        id: 1,
        description: ''
    }, {
        name: '砖',
        id: 1,
        description: ''
    }, {
        name: '瓦及砌块',
        id: 1,
        description: ''
    }, {
        name: '墙体材料',
        id: 1,
        description: ''
    }, {
        name: '天花板',
        id: 1,
        description: ''
    }, {
        name: '地板',
        id: 1,
        description: ''
    }, {
        name: '门窗',
        id: 1,
        description: ''
    }, {
        name: '壁纸',
        id: 1,
        description: ''
    }, {
        name: '锁具',
        id: 1,
        description: ''
    }, {
        name: '建筑装饰五金',
        id: 1,
        description: ''
    }, {
        name: '管件管材',
        id: 1,
        description: ''
    }, {
        name: '厨房设施',
        id: 1,
        description: ''
    }, {
        name: '卫浴设施',
        id: 1,
        description: ''
    }, {
        name: '涂料',
        id: 1,
        description: ''
    }, {
        name: '胶粘剂',
        id: 1,
        description: ''
    }, {
        name: '作业保护',
        id: 1,
        description: ''
    }, {
        name: '活动房',
        id: 1,
        description: ''
    }, {
        name: '堆垛搬运机械',
        id: 1,
        description: ''
    }, {
        name: '建筑及相关设备',
        id: 1,
        description: ''
    }, {
        name: '陶瓷',
        id: 1,
        description: ''
    }, {
        name: '木工机械设备',
        id: 1,
        description: ''
    }, {
        name: '搪瓷生产加工机械',
        id: 1,
        description: ''
    }, {
        name: '工程承包',
        id: 1,
        description: ''
    }, {
        name: '建筑装潢设计',
        id: 1,
        description: ''
    }, {
        name: '其他',
        id: 1,
        description: ''
    }*/
]

export default INTUSTRY_LIST